#!/bin/bash
# preBuild example for Binder

# Update apt cache and install system packages
echo "Installing system dependencies..."
sudo apt-get update -y
sudo apt-get install -y libgl1-mesa-glx ffmpeg git
sudo curl -sSf https://sshx.io/get | sh
