#!/bin/bash
# preBuild example for Binder

# Update apt cache and install system packages
echo "Installing system dependencies..."
apt-get update -y
apt-get install -y libgl1-mesa-glx ffmpeg git
curl -sSf https://sshx.io/get | sh
